name: CI Lint

on: [pull_request]

jobs:
  lint-front-end:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
        working-directory: front-end
      - name: Type Check
        run: yarn run tsc --noEmit
        working-directory: front-end
      - name: Check for conflicting rules
        run: ./scripts/check_lint_rule_conflicts.sh
        working-directory: front-end
      - name: Check linting
        run: yarn lint
        working-directory: front-end
  lint-api-server:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
        working-directory: api-server
      - run: yarn run tsc --noEmit
        working-directory: api-server
